spring:
  application:
    name: food_delivery
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
          github:
            client-id: ${GIT_CLIENT_ID}
            client-secret: ${GIT_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
            client-name: GitHub
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

springdoc:
  cache:
    disabled: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret-key: f8bcd7f7853659ebe3e7777c9229e3e0f944820e76de3bb0181ed0fec1fb5f41
    expiration-time: 900000
    refresh-expiration-time: 86400000

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
          github:
            client-id: ${GIT_CLIENT_ID}
            client-secret: ${GIT_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
            client-name: GitHub
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret-key: f8bcd7f7853659ebe3e7777c9229e3e0f944820e76de3bb0181ed0fec1fb5f41
    expiration-time: 900000
    refresh-expiration-time: 86400000